name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./client
          start: npm run start
          working-directory: ./client
          wait-on: 'http://localhost:3000'
          browser: chrome
