name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Remove node_modules
        run: rm -rf ./client/node_modules && rm -rf ./server/node_modules && rm -rf ./node_modules
      - name: Install dependencies Client
        working-directory: ./client
        run: |
          for i in {1..5}; do npm ci && break || sleep 15; done
      - name: Install dependencies Server
        working-directory: ./server
        run: |
          for i in {1..5}; do npm ci && break || sleep 15; done
      - name: Install dependencies
        run: |
          for i in {1..5}; do npm ci && break || sleep 15; done
      - name: Start the App
        run: npm run start &
        working-directory: ./
      - name: Verify the App is running
        run: sleep 10 && curl http://localhost:3000
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: 'http://localhost:3000'
          working-directory: ./client
              