name: Cypress Tests

on: push

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies Client
              working-directory: ./client
              run: npm i
            - name: Install dependencies Server
              working-directory: ./server
              run: npm i
        
            - name: Install dependencies
              run: npm install
            - name: Run Cypress tests
              uses: cypress-io/github-action@v6
              with:
                start: npm run start
                browser: chrome
                wait-on: 'http://localhost:3000'
                working-directory: ./client
              