name: Cypress Tests

on: push

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Clear npm cache
              run: npm cache clean --force
            - name: Install dependencies Client
              working-directory: ./client
              run: npm i
            - name: Install dependencies Server
              working-directory: ./server
              run: npm i
        
            - name: Install dependencies
              run: npm install
            - name: Start the App
              run: npm run start &
              working-directory: ./
            - name: Verify the App is running
              run: sleep 10 && curl http://localhost:3000
            - name: Run Cypress tests
              uses: cypress-io/github-action@v6
              with:
                browser: chrome
                wait-on: 'http://localhost:3000'
                working-directory: ./client
              