name: CI and CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-and-deploy:
   runs-on: ubuntu-latest
   steps:
    # Checkout the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.1
            

    # Install dependencies client
    - name: Install dependencies Client
      working-directory: ./client
      run: npm i

    # Install dependencies server
    - name: Install dependencies Server
      working-directory: ./server
      run: npm i

    - name: Install dependencies and start app
      working-directory: ./
      run: |
        npm i
        npm start &

    - name: Wait for app to start
      run: npx wait-on http://localhost:3000

    - name: Run tests
      working-directory: ./
      run: npm test
    
    - name: Stop app
      run: npm stop

    - name: Build client
      run: |
       npm build
       npm deploy